stops.bin: CreateQuadTree.class ../combined-stops.json
	java CreateQuadTree
	
CreateQuadTree.class: CreateQuadTree.java
	javac CreateQuadTree.java
	
clean:
	rm *.class stops.bin busradar/madison/*.class

